name: Build Dynamic Library (Android)

on:
  push:
    branches:
      - "**"

jobs:
  linux-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Build Swift Package on Android"
        uses: skiptools/swift-android-action@v2
        with:
          swift-version: "5.9"
          build-tests: false
          run-tests: false
